### ISSUE TITLE
voodoo-do: Cmi_format.Error

### ISSUE THREAD

**Issue by jonludlam** [ocaml-doc/voodoo#18] opened 2021-06-20 11:40 UTC
Job:
```
2021-06-20 10:09.31: New job: Voodoo do menhir.20181006; c02b2946c7ae2218173522d36a3958d2
```

https://docs.ci.ocaml.org/job/2021-06-20/100931-voodoo-do-14afc2

```
/home/opam/docs/: (run (shell "OCAMLRUNPARAM=b opam exec -- /home/opam/voodoo-do -p menhir -b"))
No dune: Missing
Found 0 mld pages and 273 other pages
libraries: []
odoc: internal error, uncaught exception:
      Cmi_format.Error(_)
      Raised at Cmi_format.read_cmi in file "file_formats/cmi_format.ml", line 83, characters 6-21
      Called from Odoc_odoc__Depends.for_compile_step_cmi_or_cmti in file "src/odoc/depends.ml", line 37, characters 18-62
      Called from Dune__exe__Main.Depends.Compile.list_dependencies in file "src/odoc/bin/main.ml", line 526, characters 17-72
      Called from Cmdliner_term.app.(fun) in file "cmdliner_term.ml", line 25, characters 19-24
      Called from Cmdliner.Term.run in file "cmdliner.ml", line 117, characters 32-39
voodoo-do: internal error, uncaught exception:
           (Failure
              "Error: run ['odoc' 'compile-deps'\
             \n     'prep/universes/c02b2946c7ae2218173522d36a3958d2/menhir/20181006/doc/menhir/demos/calc-dune/_build/default/.calc.eobjs/parser.cmti']: exited with 2")
           Raised at Stdlib.failwith in file "stdlib.ml", line 29, characters 17-33
           Called from Voodoo_lib__Odoc.compile_deps in file "lib/odoc.ml", line 38, characters 8-94
           Called from Voodoo_lib__Do.get_source_info in file "lib/do.ml", line 65, characters 12-34
           Called from Stdlib__list.map in file "list.ml", line 92, characters 20-23
           Called from Voodoo_lib__Listm.(>>=) in file "lib/listm.ml" (inlined), line 7, characters 31-45
           Called from Voodoo_lib__Do.run in file "lib/do.ml", line 185, characters 12-43
           Called from Cmdliner_term.app.(fun) in file "cmdliner_term.ml", line 25, characters 19-24
           Called from Cmdliner.Term.run in file "cmdliner.ml", line 117, characters 32-39
"/bin/bash" "-c"
"OCAMLRUNPARAM=b opam exec -- /home/opam/voodoo-do -p menhir -b" failed with exit status 125
2021-06-20 10:12.12: Job failed: Failed: Build failed
```

**Comment by jonludlam** [comment] 2021-06-20 11:40
and https://docs.ci.ocaml.org/job/2021-06-20/100931-voodoo-do-99119a

**Comment by tmattio** [comment] 2023-01-08 16:16
Added a reproduction test in https://github.com/ocaml-doc/voodoo/pull/46/commits/56e9cd345f53095de76198eadcfaccd07d634967 (staging branch)

**Comment by tmcgilchrist** [comment] 2023-05-02 06:04
Similar error from `odoc` from this [build](https://docs.ci.ocaml.org/job/2023-05-01/141420-voodoo-do-647de6).

```
compile command: odoc compile
                   prep/universes/85657c8c1ff30923db6956dace68ec87/timmy/1.0.0/lib/timmy/timmy__Type.cmt
                   -o compile/p/timmy/1.0.0/1.0.0/lib/timmy/Timmy__Type.odoc
                   --parent "doc" -I
                   compile/p/ocaml-base-compiler/4.14.1/4.14.1/lib/ocaml/ -I
                   compile/p/ptime/1.1.0/1.1.0/lib/ptime/ -I
                   compile/p/timmy/1.0.0 -I
                   compile/p/timmy/1.0.0/1.0.0/lib/timmy/ -I
                   compile/u/105570de33f9e51159404c19508e56d5/fmt/0.9.0/0.9.0/lib/fmt/
                   -I
                   compile/u/85648556adcb72c4a188ee9f840fa391/base/v0.15.1/v0.15.1/lib/base/
                   -I
                   compile/u/85648556adcb72c4a188ee9f840fa391/base/v0.15.1/v0.15.1/lib/base/base_internalhash_types/
                   -I
                   compile/u/85648556adcb72c4a188ee9f840fa391/base/v0.15.1/v0.15.1/lib/base/caml/
                   -I
                   compile/u/85648556adcb72c4a188ee9f840fa391/base/v0.15.1/v0.15.1/lib/base/shadow_stdlib/
                   -I
                   compile/u/bb02fc4780df68aa0ca19a32eca39daf/ppx_deriving/5.2.1/5.2.1/lib/ppx_deriving/runtime/
                   -I
                   compile/u/efb7484280b8d1f8589b4b784d9b12a9/result/1.5/1.5/lib/result/
                   -I
                   compile/u/efb7484280b8d1f8589b4b784d9b12a9/sexplib0/v0.15.1/v0.15.1/lib/sexplib0/
odoc: internal error, uncaught exception:
      File "src/loader/cmi.ml", line 939, characters 21-27: Assertion failed
      Raised at Odoc_loader__Cmi.read_module_type in file "src/loader/cmi.ml", line 939, characters 21-33
      Called from Odoc_loader__Cmt.read_module_expr in file "src/loader/cmt.ml", line 371, characters 18-85
      Called from Odoc_loader__Cmt.read_module_expr_maybe_canonical in file "src/loader/cmt.ml", line 410, characters 10-53
      Called from Odoc_loader__Cmt.read_module_binding in file "src/loader/cmt.ml", line 431, characters 10-81
      Called from Odoc_loader__Cmt.read_structure_item in file "src/loader/cmt.ml", line 497, characters 14-47
      Called from Odoc_loader__Cmt.read_structure.(fun) in file "src/loader/cmt.ml", line 579, characters 24-61
      Called from Stdlib__List.fold_left in file "list.ml", line 121, characters 24-34
      Called from Odoc_loader__Cmt.read_structure in file "src/loader/cmt.ml", line 577, characters 4-127
      Called from Odoc_loader__Cmt.read_implementation in file "src/loader/cmt.ml", line 592, characters 4-74
      Called from Odoc_loader.read_cmt in file "src/loader/odoc_loader.ml", line 145, characters 34-74
      Called from Odoc_loader.wrap_errors.(fun) in file "src/loader/odoc_loader.ml", line 164, characters 10-14
      Called from Odoc_model__Error.catch in file "src/model/error.ml", line 54, characters 21-27
      Called from Odoc_model__Error.catch_warnings.(fun) in file "src/model/error.ml", line 89, characters 18-22
      Called from Odoc_model__Error.with_ref in file "src/model/error.ml", line 67, characters 12-16
      Re-raised at Odoc_model__Error.with_ref in file "src/model/error.ml", line 72, characters 4-11
      Called from Odoc_odoc__Compile.resolve_and_substitute in file "src/odoc/compile.ml", line 87, characters 4-31
      Called from Odoc_model__Error.catch in file "src/model/error.ml", line 54, characters 21-27
      Called from Odoc_model__Error.catch_warnings.(fun) in file "src/model/error.ml", line 89, characters 18-22
      Called from Odoc_model__Error.with_ref in file "src/model/error.ml", line 67, characters 12-16
      Re-raised at Odoc_model__Error.with_ref in file "src/model/error.ml", line 72, characters 4-11
      Called from Odoc_odoc__Compile.compile.(fun) in file "src/odoc/compile.ml", line 239, characters 6-136
      Called from Cmdliner_term.app.(fun) in file "cmdliner_term.ml", line 24, characters 19-24
      Called from Cmdliner_term.app.(fun) in file "cmdliner_term.ml", line 22, characters 12-19
      Called from Cmdliner_eval.run_parser in file "cmdliner_eval.ml", line 34, characters 37-44
voodoo-do: internal error, uncaught exception:
           Failure("Error: run ['odoc' 'compile'\n     'prep/universes/85657c8c1ff30923db6956dace68ec87/timmy/1.0.0/lib/timmy/timmy__Type.cmt'\n     '-o' 'compile/p/timmy/1.0.0/1.0.0/lib/timmy/Timmy__Type.odoc' '--parent'\n     '\"doc\"' '-I' 'compile/p/ocaml-base-compiler/4.14.1/4.14.1/lib/ocaml/'\n     '-I' 'compile/p/ptime/1.1.0/1.1.0/lib/ptime/' '-I'\n     'compile/p/timmy/1.0.0' '-I' 'compile/p/timmy/1.0.0/1.0.0/lib/timmy/'\n     '-I'\n     'compile/u/105570de33f9e51159404c19508e56d5/fmt/0.9.0/0.9.0/lib/fmt/'\n     '-I'\n     'compile/u/85648556adcb72c4a188ee9f840fa391/base/v0.15.1/v0.15.1/lib/base/'\n     '-I'\n     'compile/u/85648556adcb72c4a188ee9f840fa391/base/v0.15.1/v0.15.1/lib/base/base_internalhash_types/'\n     '-I'\n     'compile/u/85648556adcb72c4a188ee9f840fa391/base/v0.15.1/v0.15.1/lib/base/caml/'\n     '-I'\n     'compile/u/85648556adcb72c4a188ee9f840fa391/base/v0.15.1/v0.15.1/lib/base/shadow_stdlib/'\n     '-I'\n     'compile/u/bb02fc4780df68aa0ca19a32eca39daf/ppx_deriving/5.2.1/5.2.1/lib/ppx_deriving/runtime/'\n     '-I'\n     'compile/u/efb7484280b8d1f8589b4b784d9b12a9/result/1.5/1.5/lib/result/'\n     '-I'\n     'compile/u/efb7484280b8d1f8589b4b784d9b12a9/sexplib0/v0.15.1/v0.15.1/lib/sexplib0/']: exited with 2")
           Raised at Stdlib.failwith in file "stdlib.ml", line 29, characters 17-33
           Called from Voodoo_lib__Do.run.compile in file "src/voodoo/do.ml", line 213, characters 8-96
           Called from Stdlib__List.fold_left in file "list.ml", line 121, characters 24-34
           Called from Voodoo_lib__Do.run.compile in file "src/voodoo/do.ml", line 203, characters 8-243
           Called from Stdlib__List.fold_left in file "list.ml", line 121, characters 24-34
           Called from Voodoo_lib__Do.run.compile in file "src/voodoo/do.ml", line 203, characters 8-243
           Called from Stdlib__Map.Make.fold in file "map.ml", line 321, characters 19-42
           Called from Stdlib__Map.Make.fold in file "map.ml", line 321, characters 26-41
           Called from Stdlib__Map.Make.fold in file "map.ml", line 321, characters 26-41
           Called from Voodoo_lib__Do.run in file "src/voodoo/do.ml", line 217, characters 17-60
           Called from Cmdliner_term.app.(fun) in file "cmdliner_term.ml", line 24, characters 19-24
           Called from Cmdliner_eval.run_parser in file "cmdliner_eval.ml", line 34, characters 37-44
"/bin/bash" "-c" "(OCAMLRUNPARAM=b opam exec -- /home/opam/voodoo-do -p timmy -b ) && (shopt -s nullglob && ((tar -cvf compile/p/timmy/1.0.0.tar compile/p/timmy/1.0.0/*  && rm -R compile/p/timmy/1.0.0/* && mv compile/p/timmy/1.0.0.tar compile/p/timmy/1.0.0/content.tar) || (echo 'Empty directory'))) && (mkdir -p linked && mkdir -p epoch-161b629bd52882d49754967e7f795117 && mv linked epoch-161b629bd52882d49754967e7f795117/) && (mkdir -p epoch-161b629bd52882d49754967e7f795117/linked/p/timmy/1.0.0) && (shopt -s nullglob && ((tar -cvf epoch-161b629bd52882d49754967e7f795117/linked/p/timmy/1.0.0.tar epoch-161b629bd52882d49754967e7f795117/linked/p/timmy/1.0.0/*  && rm -R epoch-161b629bd52882d49754967e7f795117/linked/p/timmy/1.0.0/* && mv epoch-161b629bd52882d49754967e7f795117/linked/p/timmy/1.0.0.tar epoch-161b629bd52882d49754967e7f795117/linked/p/timmy/1.0.0/content.tar) || (echo 'Empty directory')))" failed with exit status 125
2023-05-01 14:14.50: Job failed: Failed: Build failed
```

**Comment by sabine** [comment] 2023-06-21 12:19
Menhir seems to be doing fine now. I'm closing this in favor of https://github.com/ocaml-doc/voodoo/issues/60

**Closed by sabine** 2023-06-21 12:19 UTC
